env:
  WORKING_DIRECTORY: angular

jobs:
  build:
    name: build_angular
    runs-on: ubuntu-18.04
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2.1.0
      - name: npm_install
        run: npm clean-install
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: npm_lint
        run: npm run lint
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: npm_build
        run: npm run build
        working-directory: ${{ env.WORKING_DIRECTORY }}

  test:
    name: test_angular
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2.1.0
      - name: npm_install
        run: npm clean-install
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: npm_update
        run: npm run update
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: npm_test
        run: npm run test
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: npm_e2e
        run: npm run e2e
        working-directory: ${{ env.WORKING_DIRECTORY }}

  analyze:
    name: analyze_angular
    needs: [build, test]
    runs-on: ubuntu-18.04
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2.1.0
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: sonar_scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ env.WORKING_DIRECTORY }}

  pack:
    name: pack_job
    needs: [analyze]
    runs-on: ubuntu-18.04
    steps:
      - name: pack_script
        run: echo 'pack script'

name: integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
